language: python
python:
  - "3.8"
cache: pip
install:
  - pip install coverage --quiet
  - pip install coveralls --quiet
  - pip install -r requirements.txt --quiet
script:
  - bash -e tests/build.sh
after_success:
  coveralls
notifications:
  webhooks:
    https://alexandrainstituttet.webhook.office.com/webhookb2/f20b87b7-f448-44d4-bea7-16940ecab89c@4bda23cd-4a87-419b-a47d-7673130b2884/TravisCI/7a29047836fe4ea88b294b459026f2c4/5fe789ef-978a-49af-91b0-4feb326aa087
